#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --system live \
    --distribution trixie \
    --architectures amd64 \
    --linux-flavours amd64 \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free non-free-firmware" \
    --bootloaders "grub-efi" \
    --uefi-secure-boot auto \
    --debian-installer none \
    --firmware-chroot true \
    --apt-recommends true \
    --apt-indices true \
    --security true \
    --updates true \
    --memtest none \
    --win32-loader false \
    --bootappend-live "boot=live components quiet username=user hostname=nextraos locales=en_US.UTF-8" \
    --iso-application "NextraOS Live" \
    --iso-publisher "NextraOS Project" \
    --iso-volume "NextraOS $(date +%Y%m%d)" \
    "${@}"
