---
# Partition configuration for NextraOS
# Use 512MB EFI partition for UEFI systems
efiSystemPartitionSize: 512

# Allow use of alongside, replace, etc.
kpmcoreInternal: true

# Prevent installation on USB devices by default
avoidInternalDisk: true
